#!/bin/bash

args="$*"
repository=$(echo $args | cut -d " " -f 1)
run_id=$(echo $args | cut -d " " -f 2)
slack_alerts_channel=$(echo $args | cut -d " " -f 3)
slack_webhook_url=$(echo $args | cut -d " " -f 4)

notify_slack() {
  curl -s -d "{ \"channel\": \"$slack_alerts_channel\", \"text\": \"$1\" }" -H "Content-Type: application/json" -X POST "$slack_webhook_url"
  echo "Message sent to Slack"
}

gem install bundler-audit
bundler-audit update
bundler-audit

if [ $? -eq 0 ]; then
  echo "No vulnerabilities found."
else
  run_url=https://github.com/$repository/actions/runs/$run_id
  echo "Gem vulnerabilities found. Check GitHub for details: $run_url"
  notify_slack "Gem vulnerabilities found. Check GitHub for details: $run_url"
  exit 1
fi
