#!/bin/bash

run_url=https://github.com/$1/actions/runs/$2
slack_alerts_channel=$3
slack_webhook_url=$4

notify_slack() {
  curl -s -d "{ \"channel\": \"$slack_alerts_channel\", \"text\": \"$1\" }" -H "Content-Type: application/json" -X POST "$slack_webhook_url"
  echo "Message sent to Slack"
}

gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")
bundle outdated --strict

if [ $? -eq 0 ]; then
  echo "No outdated gems found."
else
  echo "Outdated gems found. Check GitHub for details: $run_url"
  notify_slack "Outdated gems found. Check GitHub for details: $run_url"
  exit 1
fi
