name: Build
on:
  workflow_dispatch:

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        docker build -f Dockerfile -t ghcr.io/dispatchinc/ninny:latest .
        docker push ghcr.io/dispatchinc/ninny:latest
