title = 'GitLeaks Allowlist'

[allowlist]
  description = 'A list of commits and secrets to skip when scanning for secrets'
  commits = [
    'ExampleCommit'
  ]
  regexes = [
    'ExampleSecret'
  ]
