name: Scheduled
on:
  schedule:
    - cron: "0 4 * * 1" # 4am UTC on Mondays (10pm/11pm CT on Sundays)

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - run: |
        gem install bundler-audit
        bundler-audit update
        bundler-audit
  bundle-outdated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - run: bundle outdated --strict
