name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, 3.0]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
  pronto:
    if: github.EVENT_NAME == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: HeRoMo/pronto-action@v1.13.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  gitleaks:
    if: github.EVENT_NAME == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        curl -H "Accept: application/vnd.github.v3.raw" \
          -L "https://api.github.com/repos/zricethezav/gitleaks/contents/config/gitleaks.toml?ref=${{ env.GITLEAKS_REF }}" \
          >> ${{ github.WORKSPACE }}/.github/workflows/original.toml
        sed "/\[allowlist\]/,/^$/d" ${{ github.WORKSPACE }}/.github/workflows/original.toml >> ${{ github.WORKSPACE }}/.github/workflows/official.toml
        cat .gitlab/ci/gitleaks.toml >> .gitlab/ci/official.toml
        echo "LOG_OPTS='^origin/main ${{ github.EVENT.PULL_REQUEST.HEAD.SHA }}'" >> $GITHUB_ENV
    - name: GitLeaks
      uses: addnab/docker-run-action@v3
      with:
        image: zricethezav/gitleaks:v8.0.4
        options: -v ${{ github.WORKSPACE }}:/app
        run: |
          cd /app
          gitleaks detect --verbose --config='.github/workflows/official.toml' \
                   --source='./' --log-opts='${{ env.LOG_OPTS }}'
