name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, 3.0]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
  pronto:
    if: github.EVENT_NAME == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: HeRoMo/pronto-action@v1.13.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  gitleaks:
    if: github.EVENT_NAME == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        if [[ ${{ github.REF }} == 'refs/heads/main' ]]; then
          CURRENT_COMMIT="${{ github.SHA }}"
        else
          CURRENT_COMMIT="${{ github.EVENT.PULL_REQUEST.HEAD.SHA }}"
        fi
        echo "COMMITS=$(
          git rev-list $CURRENT_COMMIT ^origin/main | sed 's/^\|$//g' | paste -sd, -
        )" >> $GITHUB_ENV
    - name: GitLeaks
      uses: addnab/docker-run-action@v3
      with:
        image: zricethezav/gitleaks
        options: -v ${{ github.WORKSPACE }}:/app
        run: |
          cd /app
          gitleaks --verbose --additional-config='.github/workflows/gitleaks.toml' \
                   --path='./' --commits='${{ env.COMMITS }}'
